name: Build JAR with Maven

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        repository: 'ZUGFeRD/mustangproject'
        persist-credentials: false

    - name: Set up JDK
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520  # v5.4.0
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package -Dmaven.test.failure.ignore=true

    - name: Upload JAR artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: Mustang-CLI-SNAPSHOT
        path: Mustang-CLI/target/Mustang-CLI-*-SNAPSHOT.jar
        archive: false
